language: objective-c
osx_image: xcode12
xcode_sdk: iphonesimulator14.0

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod cache clean Paparazzo
  - pod cache clean ImageSource
  - pod update --project-directory=Example --verbose
script:
  - set -o pipefail
  - xcodebuild build -workspace Example/PaparazzoExample.xcworkspace -scheme PaparazzoExample ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty
  - xcodebuild build -workspace Example/PaparazzoExample.xcworkspace -scheme PaparazzoExample_NoMarshroute ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty
  - xcodebuild build -workspace Example/PaparazzoExample.xcworkspace -scheme PaparazzoExample_Storyboard ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty
